version: '3.5'

networks:
  db-net:
    name: my_youtube_db-net
    internal: true
  proxy:
    external: 
      name: docker-compose_proxy

services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    networks:
      - db-net
    volumes:
      - ./webapp/db/sql/data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: youtube
      MYSQL_PASSWORD: ${DB_PASS}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./webapp/db/elastic:/usr/share/elasticsearch/data
    networks:
      - db-net

  mail_sender:
    image: catatnight/postfix
    container_name: mail_sender
    expose:
      - 25
    environment:
      smtp_user: ${SMTP_USER}:${SMTP_PASS}
      maildomain: ${SMTP_SERVER}
    networks:
      - proxy

  map_bck-end:
    build: ./webapp/api
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    depends_on:
      - database
    networks:
      - db-net
      - proxy
    volumes:
      - ./webapp/api:/home/api/:ro
      - ./webapp/video:/home/video/
    environment:
      VIRTUAL_HOST: api.${DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
      API_MOD: ${API_MOD}
      API_PASS: password
      API_ADM: ${API_ADM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_SERVER: ${SMTP_SERVER}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  video:
      image: nginx
      container_name: video
      restart: always
      networks:
        - proxy
      volumes:
        - ./webapp/video:/usr/share/nginx/html:ro
      environment:
        VIRTUAL_HOST: video.${DOMAIN}
        VIRTUAL_PORT: 8080
        LETSENCRYPT_HOST: video.${DOMAIN}
        LETSENCRYPT_EMAIL: ${EMAIL}


volumes:
   db:
